//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBank
    {
        public TblBank()
        {
            this.TblBankProcesses = new HashSet<TblBankProcesses>();
        }
    
        public int BankId { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankTitle { get; set; }
        public Nullable<decimal> BankBalance { get; set; }
    
        public virtual ICollection<TblBankProcesses> TblBankProcesses { get; set; }
    }
}
